Item.create!(name: "+5 Dexterity Vest", sell_in: 10, quality: 20)
Item.create!(name: "Aged Brie", sell_in: 2, quality: 0)
Item.create!(name: "Elixir of the Mongoose", sell_in: 5, quality: 7)
Item.create!(name: "Sulfuras, Hand of Ragnaros", sell_in: 0, quality: 80)
Item.create!(name: "Sulfuras, Hand of Ragnaros", sell_in: -1, quality: 80)
Item.create!(name: "Backstage passes to a TAFKAL80ETC concert", sell_in: 15, quality: 20)
Item.create!(name: "Backstage passes to a TAFKAL80ETC concert", sell_in: 10, quality: 49)
Item.create!(name: "Backstage passes to a TAFKAL80ETC concert", sell_in: 5, quality: 49)
Item.create!(name: "Conjured Mana Cake", sell_in: 3, quality: 6)
